dist: trusty
sudo: false
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -version 1.12.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  directories:
    - node_modules
    - ~/.yarn
script:
  - yarn
  - yarn test --verbose
